import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  learnSidebar: [
    {
      type: 'category',
      label: 'DSA',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Arrays & Strings',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'dsa/arrays-strings/index' },
          items: [
            'dsa/arrays-strings/two-pointers',
            'dsa/arrays-strings/sliding-window',
            'dsa/arrays-strings/hashmap',
            'dsa/arrays-strings/prefix-sum',
          ],
        },
        {
          type: 'category',
          label: 'Lists & Trees',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'dsa/lists-trees/index' },
          items: [
            'dsa/lists-trees/linked-list',
            'dsa/lists-trees/stack',
            'dsa/lists-trees/queue-deque',
            'dsa/lists-trees/binary-tree',
            'dsa/lists-trees/heap-preview',
          ],
        },
        {
          type: 'category',
          label: 'Heap & Trie',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'dsa/heap-trie/index' },
          items: [
            'dsa/heap-trie/heap',
            'dsa/heap-trie/trie',
          ],
        },
        {
          type: 'category',
          label: 'Graphs & DP',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'dsa/graphs-dp/index' },
          items: [
            'dsa/graphs-dp/graph-traversal',
            'dsa/graphs-dp/binary-search',
            'dsa/graphs-dp/dynamic-programming',
            'dsa/graphs-dp/backtracking',
          ],
        },
        {
          type: 'category',
          label: 'More Patterns',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'dsa/more-patterns/index' },
          items: [
            'dsa/more-patterns/intervals',
            'dsa/more-patterns/matrix-traversal',
            'dsa/more-patterns/bit-manipulation',
          ],
        },
        'dsa/problem-checklist',
        'dsa/practice-solutions',
      ],
    },
    {
      type: 'category',
      label: 'System Design',
      collapsible: true,
      collapsed: true,
      items: [
        'system-design/fundamentals',
        'system-design/building-blocks',
        'system-design/advanced-patterns',
        'system-design/cases-social-infra',
        'system-design/cases-media-storage',
        'system-design/cases-search-payments',
        'system-design/low-level-design',
      ],
    },
    {
      type: 'category',
      label: 'Skills',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Java',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'java/index' },
          items: [
            'java/core',
            'java/concurrency',
            'java/modern',
            'java/interview-qa',
          ],
        },
        {
          type: 'category',
          label: 'Kotlin',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'kotlin/index' },
          items: [
            'kotlin/basics',
            'kotlin/data-sealed',
            'kotlin/coroutines',
            'kotlin/functional',
            'kotlin/java-interop',
          ],
        },
        {
          type: 'category',
          label: 'Design Patterns',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'java/design-patterns/index' },
          items: [
            'java/design-patterns/solid',
            {
              type: 'category',
              label: 'Creational',
              collapsible: true,
              collapsed: true,
              link: { type: 'doc', id: 'java/design-patterns/creational/index' },
              items: [
                'java/design-patterns/creational/mental-model',
                'java/design-patterns/creational/singleton',
                'java/design-patterns/creational/factory-method',
                'java/design-patterns/creational/abstract-factory',
                'java/design-patterns/creational/builder',
                'java/design-patterns/creational/prototype',
              ],
            },
            {
              type: 'category',
              label: 'Structural',
              collapsible: true,
              collapsed: true,
              link: { type: 'doc', id: 'java/design-patterns/structural/index' },
              items: [
                'java/design-patterns/structural/mental-model',
                'java/design-patterns/structural/adapter',
                'java/design-patterns/structural/bridge',
                'java/design-patterns/structural/composite',
                'java/design-patterns/structural/decorator',
                'java/design-patterns/structural/facade',
                'java/design-patterns/structural/flyweight',
                'java/design-patterns/structural/proxy',
              ],
            },
            {
              type: 'category',
              label: 'Behavioral',
              collapsible: true,
              collapsed: true,
              link: { type: 'doc', id: 'java/design-patterns/behavioral/index' },
              items: [
                'java/design-patterns/behavioral/mental-model',
                'java/design-patterns/behavioral/chain-of-responsibility',
                'java/design-patterns/behavioral/command',
                'java/design-patterns/behavioral/iterator',
                'java/design-patterns/behavioral/mediator',
                'java/design-patterns/behavioral/memento',
                'java/design-patterns/behavioral/observer',
                'java/design-patterns/behavioral/state',
                'java/design-patterns/behavioral/strategy',
                'java/design-patterns/behavioral/template-method',
                'java/design-patterns/behavioral/visitor',
              ],
            },
            'java/design-patterns/architectural',
          ],
        },
        {
          type: 'category',
          label: 'Spring',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'spring/index' },
          items: [
            'spring/core-di',
            'spring/transactions',
            'spring/rest-api',
            'spring/security',
            'spring/data-jpa',
            'spring/observability',
            'spring/testing',
            'spring/docker',
            'spring/interview-qa',
          ],
        },
        {
          type: 'category',
          label: 'Quarkus',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'quarkus/index' },
          items: [
            'quarkus/fundamentals',
            'quarkus/cdi-di',
            'quarkus/rest-reactive',
            'quarkus/panache',
            'quarkus/native-image',
            'quarkus/vs-spring',
          ],
        },
        {
          type: 'category',
          label: 'Microservices',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'microservices/index' },
          items: [
            'microservices/fundamentals',
          ],
        },
        {
          type: 'category',
          label: 'SQL',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'sql/index' },
          items: [
            'sql/fundamentals',
            'sql/joins',
            'sql/aggregations',
            'sql/subqueries',
            'sql/ctes',
            'sql/window-functions',
            'sql/optimization',
            'sql/practice',
          ],
        },
        {
          type: 'category',
          label: 'GenAI',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'genai/index' },
          items: [
            'genai/overview',
            'genai/setup',
            'genai/week-1-basics',
            'genai/week-2-rag',
            'genai/week-3-agents',
            'genai/week-4-langgraph-mcp',
            'genai/week-5-finetuning',
            'genai/week-6-evals',
            'genai/week-7-capstone',
            'genai/week-8-polish',
            'genai/checklist',
            'genai/resources',
            'genai/reference',
          ],
        },
        {
          type: 'category',
          label: 'Cloud',
          collapsible: true,
          collapsed: true,
          items: [
            'cloud/aws-architecture',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Behavioral',
      collapsible: true,
      collapsed: true,
      items: ['behavioral/prep'],
    },
  ],
};

export default sidebars;
